# Generated by Django 2.0.4 on 2018-04-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('year', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('runtime', models.PositiveIntegerField(blank=True, null=True, verbose_name='Runtime (minutes)')),
                ('genres', models.ManyToManyField(to='core.genre')),
            ],
        ),
    ]
